import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Language = "es" | "en";
type Dictionary = Record<string, string>;
const dictionaries: Record<Language, Dictionary> = {
  es: {
    about: "Sobre mí", projects: "Proyectos", skills: "Habilidades", experience: "Experiencia", contact: "Contacto", terminal: "Terminal", chooseLanguage: "Elige tu idioma", spanish: "Español", english: "English", secureBoot: "ARRANQUE SEGURO", initializing: "iniciando command deck", online: "EN LÍNEA", champion: "Campeón", challenge: "Retar al campeón", choosePokemon: "Elige tu Pokémon", attack: "Atacar", restart: "Reiniciar", chooseAnother: "Elegir otro Pokémon", send: "Enviar señal", close: "Cerrar",
    profile: "Perfil", timeline: "Línea de tiempo", systemProfile: "Perfil del sistema", technicalConstellation: "Constelación técnica", skillsDescription: "Tecnologías organizadas por misión. Pasa el cursor para activar cada señal.", careerMap: "Mapa de trayectoria", careerDescription: "Selecciona un nodo para explorar cada misión profesional.", projectsExplorer: "Explorador de proyectos", newTransmission: "Nueva transmisión", messageSent: "Señal enviada", chooseRetainer: "Elige tu Pokémon retador",
    systemProfileFile: "system_profile.json",
    developerIdentity: "Identidad del desarrollador", authorizedProfileAccess: "Acceso autorizado al perfil interno del sistema.", identity: "Identidad", values: "Valores", funFacts: "Datos curiosos", profileModules: "Módulos de perfil", identityVerified: "IDENTIDAD VERIFICADA", internalDeveloperProfile: "PERFIL INTERNO DEL DESARROLLADOR", systemsEngineer: "Ingeniero de Sistemas · Desarrollador Full Stack", statusOnline: "ESTADO: EN LÍNEA", systemBoot: "ARRANQUE DEL SISTEMA", fieldOperations: "OPERACIONES DE CAMPO", fullStackUnlocked: "FULL STACK DESBLOQUEADO", currentSession: "SESIÓN ACTUAL", openMemory: "ABRIR MEMORIA", currentSessionAction: "SESIÓN ACTUAL", timeline2019: "Primer contacto profesional con el soporte y la infraestructura.", timeline2020: "La operación técnica se convirtió en mi laboratorio de aprendizaje.", scanningIdentity: "ESCANEANDO IDENTIDAD", developerPhilosophy: "filosofía-del-desarrollador.md", readOnly: "SOLO LECTURA", cleanerBot: "BOT LIMPIADOR", taskCompleted: "TAREA FINALIZADA", inOperation: "EN OPERACIÓN", commandDeck: "PANEL DE CONTROL", buildOnline: "EN LÍNEA · COMPILACIÓN 2026.08", codeMeetsCreativity: "donde el código se une a la creatividad", achievements: "Logros", documents: "Documentos", customize: "Personalizar", mail: "Correo", upcoming: "PRÓXIMAMENTE", achievementConsole: "consola_de_logros", achievementsDescription: "Tu trayectoria convertida en misiones desbloqueables.", unlocked: "DESBLOQUEADO", locked: "BLOQUEADO", achievementUnlocked: "Logro desbloqueado", nexoOnline: "en línea y explorando", talkToNexo: "habla con Nexo",
    buildWithPurpose: "Construir con propósito", valuesIntro: "Creo software para resolver problemas reales, con interfaces claras y servicios que puedan crecer con tranquilidad.", clarityOverComplexity: "claridad antes que complejidad", operationIsProduct: "la operación también es producto", learningNeverEnds: "aprender nunca termina", systemNote: "Nota de sistema", systemNoteText: "La mejor solución no es la más ruidosa: es la que las personas pueden entender, mantener y usar con confianza.", valuesQuote: "Del soporte a la arquitectura: cada problema deja una pista para construir mejor.", factOrigin: "Origen de JotaR.OS", factOriginText: "Un portafolio convertido en sistema operativo interactivo.", factFavoriteStack: "Stack favorito", factFavoriteStackText: "Java + Spring Boot + React + PostgreSQL.", factWantToLearn: "Quiero aprender", factWantToLearnText: "Cloud, n8n, arquitectura distribuida y más automatización.", factBuild: "Me gusta construir", factBuildText: "Productos útiles que unen interfaces, datos y operación.", factHobbies: "Hobbies", factHobbiesText: "Videojuegos, exploración tecnológica y crear experiencias digitales.", factCuriosity: "Curiosidad", factCuriosityText: "Un bug bien entendido suele terminar enseñando algo valioso.", creativity: "Creatividad", logic: "Lógica", testing: "Pruebas",

    availableForWork: "DISPONIBLE PARA TRABAJAR", aboutDescription1: "Ingeniero de Sistemas y desarrollador Full Stack. Diseño aplicaciones web sólidas de extremo a extremo: interfaces claras en React, servicios con Java y Spring Boot, APIs REST y datos bien modelados.", aboutDescription2: "Me caracterizo por ser una persona proactiva, responsable y orientada a resultados, con capacidad para trabajar en equipo, adaptarme a nuevos entornos y aprender constantemente. Busco aportar valor a proyectos tecnológicos donde pueda seguir creciendo profesionalmente y enfrentar nuevos retos en el desarrollo de software.", location: "Cali, Colombia",
    verifiedProfile: "Perfil verificado · Código, creatividad y aprendizaje continuo.", live: "EN VIVO", stack: "Stack", fullStack: "Full Stack", backend: "Backend", backendValue: "Java + Spring", database: "Datos", databaseValue: "SQL + NoSQL", workflow: "Flujo", workflowValue: "Git + Scrum", milestone2015: "Primer contacto profesional con la programación de software.", milestone2022: "Tecnólogo en Análisis y Desarrollo de Sistemas de Información.", milestone2024: "Ingeniería de Sistemas y evolución hacia desarrollo Full Stack.", milestoneNow: "Construyendo productos y experiencias digitales con JotaR.OS.",

    workspaceProjects: "~/workspace/projects", repositoriesReady: "repositorios · doble clic para abrir", openExplorer: "Abrir explorador", fullScreen: "Pantalla grande", previewOpened: "Vista previa abierta dentro del explorador de JotaR.OS.", code: "Código", viewLarge: "Ver en pantalla grande", projectFinance:"Proyecto de sistema de gestion de finanzas personales realizado con Spring Boot y React ", projectPokedex: "Aplicación React que consume la PokéAPI para explorar y consultar Pokémon.", projectCoop: "Actualización del sitio web institucional para una cooperativa de crédito y ahorro.", projectCoopV1: "Realizacion del sitio web institucional para una cooperativa de crédito y ahorro.", projectBot: "Bot conversacional con respuestas automáticas e interacción por WhatsApp.", projectJotar: "Este portafolio convertido en un sistema operativo interactivo con ventanas, terminal y easter eggs.",
    previewPokedex: "Pokedex // explorando criaturas", previewCoop: "COOPCOMPARTIR // plataforma comunitaria", previewBot: "BOT SERVICE // escuchando mensajes", previewJotar: "JOTAR.OS // command deck online",

    experienceDeveloper:"Desarrollador de software",experienceDeveloperDetail:"Construcción de soluciones Full Stack para operación real, conectando backend, interfaces y datos con foco en estabilidad.",experienceDeveloperFunction1:"Diseño de APIs REST y servicios Spring Boot",experienceDeveloperFunction2:"Desarrollo de módulos React y validación de flujos",experienceDeveloperFunction3:"Integración con bases de datos y soporte de despliegues",experienceDeveloperFunction4:"Trabajo ágil, documentación y mejora continua",experienceSupport:"Soporte hardware",experienceSupportDetail:"Soporte técnico a equipos POS, kioscos y redes, resolviendo incidencias desde el diagnóstico hasta la puesta en marcha.",
    experienceSupportFunction1:"Diagnóstico y mantenimiento preventivo",experienceSupportFunction2:"Configuración de dispositivos y periféricos",experienceSupportFunction3:"Análisis de logs y escalamiento de incidentes",experienceSupportFunction4:"Acompañamiento a proveedores y usuarios",experienceAssistant:"Auxiliar de sistemas",experienceAssistantDetail:"Operación y mantenimiento de la infraestructura tecnológica, con atención cercana a usuarios y equipos de campo.",experienceAssistantFunction1:"Mantenimiento de computadores y redes",experienceAssistantFunction2:"Instalación y revisión de cámaras",experienceAssistantFunction3:"Configuración de telefonía IP",
    experienceAssistantFunction4:"Inventario y soporte a usuarios",featuredFunctions:"Funciones destacadas",growthTrajectory:"Trayectoria profesional activa",experienceFooter:"Cada etapa aportó una herramienta distinta al sistema.",

    contactTitle:"Conversemos",contactDescription:"Envía una señal al sistema. Si la oportunidad encaja, responderé personalmente.",responseProtocol:"Protocolo de respuesta",responseProtocolDescription:"La señal viaja por un canal seguro y llega directamente a mi bandeja de entrada.",messageSentDescription:"El mensaje llegó correctamente. Gracias por escribir.",sendAnother:"Enviar otra",secureChannel:"CANAL SEGURO",yourName:"Tu nombre",yourEmail:"Tu email",subject:"Asunto",opportunityMessage:"Cuéntame sobre la oportunidad...",emailError:"Configura VITE_EMAILJS_TEMPLATE_ID con el ID de tu plantilla de EmailJS.",sending:"Transmitiendo...",sendSignal:"Enviar señal",

    trainerProfile:"TRAINER PROFILE",pokemonMaster:"Jhonara · Maestro Pokémon",pokemonDescription:"Nueve regiones conquistadas y un equipo preparado para cada aventura.",regions:"Regiones",caught:"Atrapados",badges:"Medallas",certificates:"Diplomas",championTeam:"Equipo campeón",challengeChampion:"Retar al campeón",battleArena:"ARENA DE BATALLA",battleChallenge:"Reto al campeón",yourPokemon:"Tu Pokémon",championPokemon:"Campeón Jhonara",chooseAnotherPokemon:"Elegir otro Pokémon",youWon:"¡Ganaste al campeón!",championKeepsTitle:"El campeón conserva su título",absoluteChampion:"CAMPEÓN ABSOLUTO",championLevel:"CAMPEÓN LV. 99",challengeChampionTitle:"// RETO AL CAMPEÓN",battleArenaTitle:"// ARENA DE BATALLA",certificatesByRegion:"Diplomas por región",certificatePending:"Diploma pendiente de subir.",battleStarted:"¡El combate ha comenzado!",criticalHit:"💥 ¡Golpe crítico!",championDefended:"👑 El Campeón Jhonara defendió su título.",championDefeated:"🏆 ¡Has derrotado al Campeón Jhonara!",drawBattle:"⚔️ ¡Ambos Pokémon cayeron al mismo tiempo!\n\n👑 El Campeón Jhonara reconoce tu fuerza.\n\n🤝 El combate terminó en empate.",normalAttack:"Hiciste {damage} de daño. El campeón respondió con {reply}.",criticalAttack:"💥 ¡Golpe crítico! Hiciste {damage} de daño. El campeón respondió con {reply}.",

  },
  en: {
    about: "About me", projects: "Projects", skills: "Skills", experience: "Experience", contact: "Contact", terminal: "Terminal", chooseLanguage: "Choose your language", spanish: "Español", english: "English", secureBoot: "SECURE BOOT", initializing: "initializing command deck", online: "ONLINE", champion: "Champion", challenge: "Challenge champion", choosePokemon: "Choose your Pokémon", attack: "Attack", restart: "Restart", chooseAnother: "Choose another Pokémon", send: "Send signal", close: "Close",
    profile: "Profile", timeline: "Timeline", systemProfile: "System profile", technicalConstellation: "Technical constellation", skillsDescription: "Technologies organized by mission. Hover to activate each signal.", careerMap: "Career map", careerDescription: "Select a node to explore each professional mission.", projectsExplorer: "Project explorer", newTransmission: "New transmission", messageSent: "Signal sent", chooseRetainer: "Choose your challenger Pokémon",
    systemProfileFile: "system_profile.json",
    developerIdentity: "Developer Identity", authorizedProfileAccess: "Authorized access to the system's internal profile.", identity: "Identity", values: "Values", funFacts: "Fun Facts", profileModules: "Profile modules", identityVerified: "IDENTITY VERIFIED", internalDeveloperProfile: "INTERNAL DEVELOPER PROFILE", systemsEngineer: "Systems Engineer · Full Stack Developer", statusOnline: "STATUS: ONLINE", systemBoot: "SYSTEM BOOT", fieldOperations: "FIELD OPERATIONS", fullStackUnlocked: "FULL STACK UNLOCKED", currentSession: "CURRENT SESSION", openMemory: "OPEN MEMORY", currentSessionAction: "CURRENT SESSION", timeline2019: "First professional contact with support and infrastructure.", timeline2020: "Technical operations became my learning lab.", scanningIdentity: "SCANNING IDENTITY", developerPhilosophy: "developer-philosophy.md", readOnly: "READ ONLY", cleanerBot: "CLEANER BOT", taskCompleted: "TASK COMPLETED", inOperation: "IN OPERATION", commandDeck: "COMMAND DECK", buildOnline: "ONLINE · BUILD 2026.08", codeMeetsCreativity: "where code meets creativity", achievements: "Achievements", documents: "Documents", customize: "Customize", mail: "Mail", upcoming: "COMING SOON", achievementConsole: "achievement_console", achievementsDescription: "Your journey turned into unlockable missions.", unlocked: "UNLOCKED", locked: "LOCKED", achievementUnlocked: "Achievement unlocked", nexoOnline: "online and exploring", talkToNexo: "talk to Nexo",
    buildWithPurpose: "Build with purpose", valuesIntro: "I create software to solve real problems, with clear interfaces and services that can grow reliably.", clarityOverComplexity: "clarity over complexity", operationIsProduct: "operations are also product", learningNeverEnds: "learning never ends", systemNote: "System note", systemNoteText: "The best solution is not the loudest one: it is the one people can understand, maintain, and use with confidence.", valuesQuote: "From support to architecture: every problem leaves a clue to build better.", factOrigin: "Origin of JotaR.OS", factOriginText: "A portfolio turned into an interactive operating system.", factFavoriteStack: "Favorite stack", factFavoriteStackText: "Java + Spring Boot + React + PostgreSQL.", factWantToLearn: "I want to learn", factWantToLearnText: "Cloud, n8n, distributed architecture, and more automation.", factBuild: "I like building", factBuildText: "Useful products that bring together interfaces, data, and operations.", factHobbies: "Hobbies", factHobbiesText: "Video games, technology exploration, and creating digital experiences.", factCuriosity: "Curiosity", factCuriosityText: "A well-understood bug often ends up teaching something valuable.", creativity: "Creativity", logic: "Logic", testing: "Testing",

    availableForWork: "AVAILABLE FOR WORK", aboutDescription1: "Systems Engineer and Full Stack Developer. I build end-to-end web applications using React, Java, Spring Boot, REST APIs, and well-structured databases.", aboutDescription2: "I am proactive, responsible, and results-oriented, with the ability to work in teams, adapt to new environments, and continuously learn. I seek to contribute value to technological projects where I can continue to grow professionally and face new challenges in software development.",
    location: "Cali, Colombia", verifiedProfile: "Verified profile · Code, creativity and continuous learning.", live: "LIVE", stack: "Stack", fullStack: "Full Stack", backend: "Backend", backendValue: "Java + Spring", database: "Data", databaseValue: "SQL + NoSQL", workflow: "Workflow", workflowValue: "Git + Scrum", milestone2015: "First professional contact with software development.", milestone2022: "Associate Degree in Systems Analysis and Development.", milestone2024: "Systems Engineering degree and transition into Full Stack development.", milestoneNow: "Building digital products and experiences with JotaR.OS.",

    workspaceProjects: "~/workspace/projects", repositoriesReady: "repositories · double click ready", openExplorer: "Open explorer", fullScreen: "Full screen", previewOpened: "Preview opened inside JotaR.OS explorer.", code: "Source code", viewLarge: "View full screen", projectFinance:"Personal finance project with Spring Boot and React. ", projectPokedex: "React application that consumes the PokéAPI to explore and search Pokémon.", projectCoop: "Updated institutional website for a savings and credit cooperative.", projectCoopV1: "Development of the corporate website for a savings and credit cooperative.", projectBot: "Conversational WhatsApp bot with automated responses.", projectJotar: "This portfolio transformed into an interactive operating system with windows, terminal and easter eggs.",
    previewPokedex: "Pokedex // exploring creatures", previewCoop: "COOPCOMPARTIR // community platform", previewBot: "BOT SERVICE // listening for messages", previewJotar: "JOTAR.OS // command deck online",
  
    experienceDeveloper:"Software Developer",experienceDeveloperDetail:"Building Full Stack solutions for real-world operations, connecting backend, interfaces and data with a focus on stability.",experienceDeveloperFunction1:"Design of REST APIs and Spring Boot services",experienceDeveloperFunction2:"Development of React modules and workflow validation",experienceDeveloperFunction3:"Database integration and deployment support",experienceDeveloperFunction4:"Agile development, documentation and continuous improvement",
    experienceSupport:"Hardware Support",experienceSupportDetail:"Technical support for POS equipment, kiosks and networks, solving incidents from diagnosis to deployment.",experienceSupportFunction1:"Diagnosis and preventive maintenance",experienceSupportFunction2:"Device and peripheral configuration",experienceSupportFunction3:"Log analysis and incident escalation",experienceSupportFunction4:"Support for vendors and end users",experienceAssistant:"Systems Assistant",experienceAssistantDetail:"Operation and maintenance of technological infrastructure with close support for users and field teams.",
    experienceAssistantFunction1:"Computer and network maintenance",experienceAssistantFunction2:"Camera installation and inspection",experienceAssistantFunction3:"IP telephony configuration",experienceAssistantFunction4:"Inventory management and user support",featuredFunctions:"Key Responsibilities",growthTrajectory:"Growth trajectory active",experienceFooter:"Each stage added a different tool to the system.",
  
    contactTitle:"Let's Talk",contactDescription:"Send a signal to the system. If the opportunity is a good fit, I'll reply personally.",responseProtocol:"Response Protocol",responseProtocolDescription:"Your message travels through a secure channel directly to my inbox.",messageSentDescription:"Your message has been delivered successfully. Thank you for reaching out.",sendAnother:"Send Another",secureChannel:"SECURE CHANNEL",yourName:"Your name",yourEmail:"Your email",subject:"Subject",opportunityMessage:"Tell me about the opportunity...",emailError:"Configure VITE_EMAILJS_TEMPLATE_ID with your EmailJS template ID.",sending:"Transmitting...",sendSignal:"Send Signal",

    trainerProfile:"TRAINER PROFILE",pokemonMaster:"Jhonara · Pokémon Master",pokemonDescription:"Nine regions conquered and a team prepared for every adventure.",regions:"Regions",caught:"Caught",badges:"Badges",certificates:"Certificates",championTeam:"Champion Team",challengeChampion:"Challenge the Champion",battleArena:"BATTLE ARENA",battleChallenge:"Challenge the Champion",yourPokemon:"Your Pokémon",championPokemon:"Champion Jhonara",chooseAnotherPokemon:"Choose Another Pokémon",youWon:"You defeated the Champion!",championKeepsTitle:"The Champion keeps the title",absoluteChampion:"ABSOLUTE CHAMPION",championLevel:"CHAMPION LV. 99",challengeChampionTitle:"// CHALLENGE THE CHAMPION",battleArenaTitle:"// BATTLE ARENA",certificatesByRegion:"Region Certificates",certificatePending:"Certificate coming soon.",battleStarted:"The battle has begun!",criticalHit:"💥 Critical Hit!",championDefended:"👑 Champion Jhonara defended the title.",championDefeated:"🏆 You defeated Champion Jhonara!",drawBattle:"⚔️ Both Pokémon fainted at the same time!\n\n👑 Champion Jhonara acknowledges your strength.\n\n🤝 The battle ended in a draw.",normalAttack:"You dealt {damage} damage. The Champion answered with {reply}.",criticalAttack:"💥 Critical hit! You dealt {damage} damage. The Champion answered with {reply}.",
  },
};

type LanguageContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem("jotar-language") as Language) || "es");
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem("jotar-language", next); document.documentElement.lang = next; };
  const value = useMemo(() => ({ language, setLanguage, t: (key: string) => dictionaries[language][key] ?? key }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};




export const useLanguage = () => { const context = useContext(LanguageContext); if (!context) throw new Error("useLanguage must be used inside LanguageProvider"); return context; };
