import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Brain, Code2, Database, FileCode2, GitBranch, MapPin, ScanLine, ShieldCheck, Sparkles, Star } from "lucide-react";
import Typewriter from "../components/common/Typewriter";
import { useLanguage } from "../i18n/LanguageContext";
import { aboutNexoMessages, announceNexoContext } from "../components/nexo/context";

type Module = "identity" | "timeline" | "values" | "facts";
const rpgStats = [["Debugging", 4, Code2], ["Refactoring", 5, Sparkles], ["Clean Code", 4, Database], ["Creatividad", 4, GitBranch], ["Lógica", 5, Brain], ["Pruebas", 3, Star]] as const;
const reveal = { hidden: { opacity: 0, y: 18, filter: "blur(6px)" }, visible: { opacity: 1, y: 0, filter: "blur(0px)" } };

const Stars = ({ level }: { level: number }) => <motion.span initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: .08 } } }} className="flex gap-0.5 text-[#13AB91]">{Array.from({ length: 5 }, (_, index) => <motion.span variants={{ hidden: { opacity: 0, scale: .3 }, visible: { opacity: 1, scale: 1 } }} key={index}><Star size={14} fill={index < level ? "currentColor" : "transparent"} className={index < level ? "" : "text-white/15"} /></motion.span>)}</motion.span>;

const Identity = ({ t }: { t: (key: string) => string }) => <motion.div variants={{ visible: { transition: { staggerChildren: .1 } } }} initial="hidden" animate="visible" className="grid gap-6 xl:grid-cols-[250px_1fr]">
  <motion.aside variants={reveal} className="relative overflow-hidden rounded-3xl border border-[#13AB91]/25 bg-[#071224]/75 p-5 shadow-[0_0_38px_rgba(19,171,145,.1)]"><motion.div animate={{ x: ["-120%", "220%"] }} transition={{ duration: 2.4, repeat: Infinity, repeatDelay: 1.8, ease: "linear" }} className="absolute inset-y-0 z-10 w-12 -skew-x-12 bg-gradient-to-r from-transparent via-[#13AB91]/25 to-transparent" /><div className="absolute inset-x-8 top-0 h-px bg-gradient-to-r from-transparent via-[#13AB91] to-transparent" /><div className="relative grid h-64 place-items-center overflow-hidden rounded-2xl border border-white/10 bg-black/30 p-3"><img src="/images/avatar.png" alt="Avatar de Jhonatan" className="h-full w-full object-contain object-center" /><motion.span animate={{ opacity: [.2, .8, .2], y: [0, 220, 0] }} transition={{ duration: 2.8, repeat: Infinity, ease: "linear" }} className="absolute left-0 right-0 h-px bg-[#13AB91] shadow-[0_0_12px_#13AB91]" /><span className="absolute bottom-3 right-3 flex h-9 w-9 items-center justify-center rounded-full border-2 border-[#071224] bg-[#13AB91] text-[#071224]"><ShieldCheck size={17} /></span></div><p className="mt-5 flex items-center gap-2 font-mono text-[10px] tracking-[.2em] text-[#13AB91]"><ScanLine size={13} /> {t("identityVerified")}</p><p className="mt-2 font-mono text-xs text-white/45">PROFILE ID · JRU-DEV-2026</p></motion.aside>
  <motion.div variants={reveal} className="rounded-3xl border border-white/10 bg-white/[.025] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] tracking-[.22em] text-[#13AB91]">{t("internalDeveloperProfile")}</p><h3 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl"><Typewriter text="Jhonatan Stiven" speed={38} /><br />Ramírez Useche</h3><p className="mt-4 text-lg text-cyan-50/85">{t("systemsEngineer")}</p><p className="mt-2 flex items-center gap-2 text-sm text-white/50"><MapPin size={15} className="text-[#E92D88]" /> {t("location")}</p></div><motion.div animate={{ boxShadow: ["0 0 0 rgba(19,171,145,0)", "0 0 22px rgba(19,171,145,.22)", "0 0 0 rgba(19,171,145,0)"] }} transition={{ duration: 2.4, repeat: Infinity }} className="rounded-2xl border border-[#13AB91]/30 bg-[#13AB91]/10 px-4 py-3"><p className="flex items-center gap-2 font-mono text-[10px] tracking-[.14em] text-[#13AB91]"><motion.span animate={{ opacity: [.35, 1, .35] }} transition={{ duration: 1.2, repeat: Infinity }} className="h-2 w-2 rounded-full bg-[#13AB91]" /> {t("statusOnline")}</p><p className="mt-2 text-sm font-semibold text-white">{t("availableForWork")}</p></motion.div></div><p className="mt-7 max-w-3xl leading-7 text-white/65">{t("aboutDescription1")}</p><p className="mt-3 max-w-3xl leading-7 text-white/48">{t("aboutDescription2")}</p><motion.div variants={{ visible: { transition: { staggerChildren: .07, delayChildren: .22 } } }} className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rpgStats.map(([label, level, Icon]) => <motion.div variants={reveal} whileHover={{ y: -3, borderColor: "rgba(19,171,145,.48)" }} key={label} className="rounded-2xl border border-white/10 bg-black/15 p-4 transition"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm text-white/75"><Icon size={15} className="text-[#13AB91]" />{label}</span><span className="font-mono text-[10px] text-white/35">LVL {level}</span></div><div className="mt-3"><Stars level={level} /></div></motion.div>)}</motion.div></motion.div>
</motion.div>;

const Timeline = ({ t }: { t: (key: string) => string }) => { const memories = [["2019", t("systemBoot"), t("timeline2019"), t("openMemory")], ["2020", t("fieldOperations"), t("timeline2020"), t("openMemory")], ["2024", t("fullStackUnlocked"), t("milestone2024"), t("openMemory")], ["NOW", t("currentSession"), t("milestoneNow"), t("currentSessionAction")]] as const; return <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: .1 } } }} className="grid gap-4 md:grid-cols-2">{memories.map(([year, title, text, action], index) => <motion.article variants={reveal} whileHover={{ y: -4, boxShadow: "0 0 28px rgba(19,171,145,.12)" }} key={year} className="relative overflow-hidden rounded-3xl border border-white/10 bg-[#071224]/70 p-6"><span className="absolute right-5 top-4 font-mono text-5xl font-black text-white/[.035]">{String(index + 1).padStart(2, "0")}</span><p className="font-mono text-2xl font-bold text-[#13AB91]">{year}</p><div className="mt-6 border-l border-[#E92D88]/55 pl-4"><p className="font-mono text-xs tracking-[.16em] text-pink-200">{title}</p><p className="mt-3 leading-6 text-white/60">{text}</p></div><button type="button" className="mt-6 font-mono text-[10px] tracking-[.18em] text-white/45">› {action}</button></motion.article>)}</motion.div>; };

const Values = ({ t }: { t: (key: string) => string }) => <motion.div variants={reveal} initial="hidden" animate="visible" className="overflow-hidden rounded-3xl border border-white/10 bg-[#050b18]"><div className="flex items-center gap-2 border-b border-white/10 bg-white/[.035] px-5 py-3"><FileCode2 size={16} className="text-[#13AB91]" /><span className="font-mono text-xs text-white/65">{t("developerPhilosophy")}</span><span className="ml-auto font-mono text-[10px] text-white/30">{t("readOnly")}</span></div><div className="space-y-6 p-6 font-mono text-sm leading-7 sm:p-8"><div><p className="text-[#E92D88]"># {t("buildWithPurpose")}</p><p className="mt-2 text-white/65">{t("valuesIntro")}</p></div><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .3 }} className="rounded-2xl border border-[#13AB91]/20 bg-[#13AB91]/[.05] p-4 text-cyan-50/80"><span className="text-[#13AB91]">const</span> developerPrinciples = [<br /><span className="pl-5 text-[#f4c95d]">"{t("clarityOverComplexity")}",</span><br /><span className="pl-5 text-[#f4c95d]">"{t("operationIsProduct")}",</span><br /><span className="pl-5 text-[#f4c95d]">"{t("learningNeverEnds")}"</span><br />];</motion.div><div><p className="text-[#E92D88]">## {t("systemNote")}</p><p className="mt-2 text-white/60">{t("systemNoteText")}</p></div><blockquote className="border-l-2 border-[#13AB91] pl-4 text-white/45">&gt; "{t("valuesQuote")}"</blockquote></div></motion.div>;

const FunFacts = ({ t }: { t: (key: string) => string }) => { const facts = [[t("factOrigin"), t("factOriginText")], [t("factFavoriteStack"), t("factFavoriteStackText")], [t("factWantToLearn"), t("factWantToLearnText")], [t("factBuild"), t("factBuildText")], [t("factHobbies"), t("factHobbiesText")], [t("factCuriosity"), t("factCuriosityText")]]; return <motion.div initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: .08 } } }} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{facts.map(([title, detail], index) => <motion.article variants={reveal} whileHover={{ y: -5, scale: 1.01 }} key={title} className="rounded-3xl border border-white/10 bg-white/[.025] p-5"><span className="font-mono text-[10px] text-[#13AB91]">FACT_{String(index + 1).padStart(2, "0")}</span><h3 className="mt-4 font-bold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{detail}</p></motion.article>)}</motion.div>; };

const Scanner = ({ t }: { t: (key: string) => string }) => <motion.div initial={{ opacity: 1 }} exit={{ opacity: 0, scale: 1.025 }} transition={{ duration: .45 }} className="absolute inset-0 z-30 grid place-items-center bg-[#030813]/95 backdrop-blur-sm"><div className="text-center"><motion.div animate={{ rotate: 360 }} transition={{ duration: 1.3, repeat: Infinity, ease: "linear" }} className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-[#13AB91]/50 border-t-[#E92D88] shadow-[0_0_28px_rgba(19,171,145,.25)]"><ScanLine size={25} className="text-[#13AB91]" /></motion.div><p className="mt-5 font-mono text-sm tracking-[.22em] text-cyan-50">{t("scanningIdentity")}<span className="about-scan-dots">...</span></p><div className="mt-3 h-px w-56 overflow-hidden bg-white/10"><motion.div animate={{ x: ["-100%", "250%"] }} transition={{ duration: .9, repeat: Infinity, ease: "easeInOut" }} className="h-full w-2/5 bg-gradient-to-r from-transparent via-[#13AB91] to-[#E92D88]" /></div></div></motion.div>;

const AboutApp = () => { const { t, language } = useLanguage(); const [activeTab, setActiveTab] = useState<Module>("identity"); const [scanning, setScanning] = useState(true); const moduleTabs: Array<{ id: Module; label: string }> = [{ id: "identity", label: t("identity") }, { id: "timeline", label: t("timeline") }, { id: "values", label: t("values") }, { id: "facts", label: t("funFacts") }]; useEffect(() => { const timer = window.setTimeout(() => setScanning(false), 1350); return () => window.clearTimeout(timer); }, []); useEffect(() => { if (!scanning) announceNexoContext(aboutNexoMessages[language][activeTab]); }, [activeTab, language, scanning]); const content = activeTab === "identity" ? <Identity t={t} /> : activeTab === "timeline" ? <Timeline t={t} /> : activeTab === "values" ? <Values t={t} /> : <FunFacts t={t} />; return <div className="relative text-white"><AnimatePresence>{scanning && <Scanner t={t} />}</AnimatePresence><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .1, duration: .45 }} className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs tracking-[.2em] text-[#13AB91]">// {t("systemProfileFile")}</p><h2 className="mt-1 text-3xl font-bold"><Typewriter text={t("developerIdentity")} speed={48} /></h2><p className="mt-2 text-sm text-white/50">{t("authorizedProfileAccess")}</p></div><nav className="flex flex-wrap rounded-xl border border-white/10 bg-black/20 p-1" aria-label={t("profileModules")}>{moduleTabs.map((tab) => <motion.button whileTap={{ scale: .96 }} key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} className={`rounded-lg px-3 py-2 text-xs transition ${activeTab === tab.id ? "bg-[#13AB91]/15 text-cyan-100 shadow-[inset_0_0_0_1px_rgba(19,171,145,.28)]" : "text-white/45 hover:text-white/75"}`}>{tab.label}</motion.button>)}</nav></motion.div><AnimatePresence mode="wait"><motion.div key={activeTab} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .28 }}>{content}</motion.div></AnimatePresence><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .6 }} className="mt-6 flex items-center gap-2 rounded-2xl border border-[#13AB91]/20 bg-[#13AB91]/[.04] p-4 text-sm text-cyan-50/75"><ShieldCheck size={18} className="text-[#13AB91]" /> {t("verifiedProfile")}</motion.div></div>; };

export default AboutApp;
