import { motion } from "framer-motion";
import { LockKeyhole, Trophy } from "lucide-react";
import { achievements } from "../data/achievements";
import { useAchievementsStore } from "../store/achievements.store";

const AchievementsApp = () => {
  const unlocked = useAchievementsStore((state) => state.unlocked);
  const isUnlocked = (id: string) => achievements.find((item) => item.id === id)?.baseUnlocked || unlocked.includes(id);
  const count = achievements.filter((achievement) => isUnlocked(achievement.id)).length;
  const progress = Math.round((count / achievements.length) * 100);
  return <div className="text-white"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-sm text-amber-300">// achievement_console</p><h2 className="mt-1 text-3xl font-bold">Logros</h2><p className="mt-2 text-sm text-white/60">Tu trayectoria convertida en misiones desbloqueables.</p></div><div className="min-w-52 rounded-2xl border border-amber-300/25 bg-amber-300/8 p-3"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-medium text-amber-100"><Trophy size={17} /> {count} / {achievements.length}</span><span className="font-mono text-xs text-amber-300">{progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-black/30"><motion.div initial={{ width: 0 }} animate={{ width: `${progress}%` }} className="h-full rounded-full bg-gradient-to-r from-amber-300 via-yellow-200 to-cyan-300" /></div></div></header><div className="grid gap-3 md:grid-cols-2">{achievements.map((achievement, index) => { const active = isUnlocked(achievement.id); return <motion.article key={achievement.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .025 }} whileHover={active ? { y: -3 } : {}} className={`group flex gap-4 rounded-2xl border p-4 transition ${active ? "border-amber-300/20 bg-gradient-to-br from-amber-300/10 to-cyan-400/5 hover:border-amber-200/50 hover:shadow-[0_0_28px_rgba(252,211,77,.12)]" : "border-white/8 bg-white/[.025] grayscale opacity-55"}`}><div className={`grid h-13 w-13 shrink-0 place-items-center rounded-xl border ${active ? "border-amber-300/30 bg-amber-300/10 text-amber-200" : "border-white/10 bg-black/20 text-white/35"}`}><img src={achievement.icon} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} className="h-8 w-8 object-contain" />{active ? <Trophy size={24} className="group-has-[img]:hidden" /> : <LockKeyhole size={22} className="group-has-[img]:hidden" />}</div><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="font-semibold">{achievement.title}</h3><span className={`rounded-full px-2 py-.5 text-[10px] ${active ? "bg-emerald-400/15 text-emerald-200" : "bg-white/8 text-white/45"}`}>{active ? "DESBLOQUEADO" : "BLOQUEADO"}</span></div><p className="mt-1 text-sm leading-5 text-white/60">{achievement.description}</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.12em] text-cyan-200/60">{achievement.category}</p></div></motion.article>; })}</div></div>;
};

export default AchievementsApp;
