import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { BriefcaseBusiness, ChevronRight, MapPinned, Sparkles } from "lucide-react";

const timeline = [
  { year: "2024 — hoy", title: "Desarrollador de software", place: "Playtechnologies", color: "cyan", detail: "Construcción de soluciones full stack para operación real, conectando backend, interfaces y datos con foco en estabilidad.", skills: ["Java", "Spring Boot", "React", "PostgreSQL"], functions: ["Diseño de APIs REST y servicios Spring Boot", "Desarrollo de módulos React y validación de flujos", "Integración con bases de datos y soporte de despliegues", "Trabajo ágil, documentación y mejora continua"] },
  { year: "2020 — 2024", title: "Soporte hardware", place: "Playtechnologies", color: "violet", detail: "Soporte técnico a equipos POS, kioscos y redes, resolviendo incidencias desde el diagnóstico hasta la puesta en marcha.", skills: ["POS", "Sunmi", "Redes", "Linux"], functions: ["Diagnóstico y mantenimiento preventivo", "Configuración de dispositivos y periféricos", "Análisis de logs y escalamiento de incidentes", "Acompañamiento a proveedores y usuarios"] },
  { year: "2019 — 2020", title: "Auxiliar de sistemas", place: "Zagacol", color: "amber", detail: "Operación y mantenimiento de la infraestructura tecnológica, con atención cercana a usuarios y equipos de campo.", skills: ["Hardware", "CCTV", "Telefonía IP"], functions: ["Mantenimiento de computadores y redes", "Instalación y revisión de cámaras", "Configuración de telefonía IP", "Inventario y soporte a usuarios"] },
];

const ExperienceApp = () => {
  const [selected, setSelected] = useState(0);
  const current = timeline[selected];
  return <div className="text-white"><div className="mb-6"><p className="font-mono text-sm text-cyan-300">// career_map.log</p><h2 className="mt-1 text-3xl font-bold">Mapa de trayectoria</h2><p className="mt-2 text-white/60">Selecciona un nodo para explorar cada misión profesional.</p></div><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><div className="relative space-y-3 border-l border-cyan-400/25 pl-7">{timeline.map((item, index) => <motion.button key={item.title} onClick={() => setSelected(index)} whileHover={{ x: 5 }} className={`relative w-full rounded-xl border p-4 text-left transition ${selected === index ? "border-cyan-300/55 bg-cyan-400/10" : "border-white/10 bg-white/5 hover:border-white/25"}`}><span className={`absolute -left-[39px] top-5 h-5 w-5 rounded-full border-4 border-[#0B1220] ${selected === index ? "bg-cyan-300" : "bg-violet-400"}`} /><div className="flex items-center gap-3"><div className="rounded-lg bg-white/10 p-2 text-cyan-300"><BriefcaseBusiness size={18} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-3"><h3 className="font-bold">{item.title}</h3><span className="font-mono text-xs text-cyan-300">{item.year}</span></div><p className="text-sm text-violet-300">{item.place}</p></div><ChevronRight size={17} className={selected === index ? "text-cyan-300" : "text-white/20"} /></div></motion.button>)}</div><AnimatePresence mode="wait"><motion.aside key={current.title} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -18 }} className="h-fit rounded-2xl border border-cyan-300/25 bg-gradient-to-br from-cyan-400/10 via-slate-950 to-violet-500/10 p-5"><div className="flex items-center justify-between"><BriefcaseBusiness className="text-cyan-300" size={26} /><span className="font-mono text-xs text-emerald-300">NODE_{String(selected + 1).padStart(2, "0")}</span></div><h3 className="mt-6 text-xl font-bold">{current.title}</h3><p className="mt-1 text-violet-300">{current.place} · {current.year}</p><p className="mt-4 text-sm leading-6 text-white/65">{current.detail}</p><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-cyan-200">Funciones destacadas</p><ul className="mt-3 space-y-2 text-sm text-white/70">{current.functions.map((fn) => <li key={fn} className="flex gap-2"><span className="text-cyan-300">›</span>{fn}</li>)}</ul><div className="mt-5 flex flex-wrap gap-2">{current.skills.map((skill) => <span key={skill} className="rounded-full border border-cyan-300/20 px-2.5 py-1 text-xs text-cyan-100">{skill}</span>)}</div><div className="mt-6 flex items-center gap-2 text-xs text-white/45"><MapPinned size={14} className="text-cyan-300" /> Growth trajectory active</div></motion.aside></AnimatePresence></div><div className="mt-6 flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-400/5 p-4 text-sm text-violet-100"><Sparkles size={17} /> Cada etapa aportó una herramienta distinta al sistema.</div></div>;
};

export default ExperienceApp;
