import { useState } from "react";
import { motion } from "framer-motion";
import { FaAngular, FaDocker, FaGitAlt, FaJava, FaJsSquare, FaLinux, FaNodeJs, FaReact } from "react-icons/fa";
import { SiJira, SiMongodb, SiPostgresql, SiSpringboot, SiTailwindcss, SiTypescript, SiVite } from "react-icons/si";

const skills = [
  { name: "Java", group: "Backend", level: 92, icon: FaJava, color: "#f59e0b" }, { name: "Spring Boot", group: "Backend", level: 87, icon: SiSpringboot, color: "#86efac" }, { name: "Node.js", group: "Backend", level: 78, icon: FaNodeJs, color: "#4ade80" },
  { name: "React", group: "Frontend", level: 88, icon: FaReact, color: "#67e8f9" }, { name: "Angular", group: "Frontend", level: 72, icon: FaAngular, color: "#fb7185" }, { name: "JavaScript", group: "Frontend", level: 86, icon: FaJsSquare, color: "#fde047" }, { name: "TypeScript", group: "Frontend", level: 74, icon: SiTypescript, color: "#60a5fa" }, { name: "Tailwind", group: "Frontend", level: 82, icon: SiTailwindcss, color: "#22d3ee" }, { name: "Vite", group: "Frontend", level: 78, icon: SiVite, color: "#c084fc" },
  { name: "PostgreSQL", group: "Data", level: 84, icon: SiPostgresql, color: "#93c5fd" }, { name: "MongoDB", group: "Data", level: 65, icon: SiMongodb, color: "#86efac" }, { name: "Git", group: "Tooling", level: 88, icon: FaGitAlt, color: "#fb923c" }, { name: "Docker", group: "Tooling", level: 68, icon: FaDocker, color: "#60a5fa" }, { name: "Linux", group: "Tooling", level: 73, icon: FaLinux, color: "#facc15" }, { name: "Jira", group: "Tooling", level: 70, icon: SiJira, color: "#818cf8" },
];

const SkillsApp = () => {
  const [active, setActive] = useState(skills[0]);
  return <div className="text-white"><div className="mb-6"><p className="font-mono text-sm text-cyan-300">// skill_radar.exe</p><h2 className="mt-1 text-3xl font-bold">Constelación técnica</h2><p className="mt-2 max-w-2xl text-white/60">Pasa por cada nodo para ver el nivel de dominio y el lugar que ocupa en mi stack.</p></div><div className="grid gap-6 lg:grid-cols-[270px_1fr]"><div className="relative flex min-h-72 items-center justify-center overflow-hidden rounded-2xl border border-cyan-400/25 bg-slate-950/60"><div className="absolute h-52 w-52 rounded-full border border-cyan-300/15" /><div className="absolute h-36 w-36 rounded-full border border-violet-300/20" /><div className="absolute h-20 w-20 rounded-full border border-dashed border-cyan-300/30" /><motion.div animate={{ rotate: 360 }} transition={{ duration: 14, repeat: Infinity, ease: "linear" }} className="absolute h-64 w-64 rounded-full border border-dashed border-violet-300/20" /><div className="relative text-center"><active.icon size={38} style={{ color: active.color }} className="mx-auto" /><p className="mt-3 font-bold">{active.name}</p><p className="font-mono text-xs text-white/45">{active.group} · {active.level}%</p><div className="mx-auto mt-3 h-1 w-28 overflow-hidden rounded-full bg-white/10"><motion.div animate={{ width: `${active.level}%` }} className="h-full rounded-full" style={{ backgroundColor: active.color }} /></div></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{skills.map((skill, index) => { const Icon = skill.icon; const selected = skill.name === active.name; return <motion.button key={skill.name} onMouseEnter={() => setActive(skill)} onFocus={() => setActive(skill)} whileHover={{ scale: 1.03, y: -3 }} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .035 }} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${selected ? "border-cyan-300/60 bg-cyan-400/10" : "border-white/10 bg-white/5 hover:border-white/25"}`}><Icon size={25} style={{ color: skill.color }} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{skill.name}</span><span className="mt-1 block h-1 overflow-hidden rounded-full bg-black/30"><span className="block h-full rounded-full" style={{ width: `${skill.level}%`, backgroundColor: skill.color }} /></span></span><span className="font-mono text-xs text-white/45">{skill.level}%</span></motion.button>; })}</div></div></div>;
};

export default SkillsApp;
