import { useState } from "react";
import { motion } from "framer-motion";
import { FaAngular, FaBootstrap, FaCode, FaCss3Alt, FaDocker, FaGitAlt, FaGithub, FaHtml5, FaJava, FaJsSquare, FaLinux, FaNodeJs, FaPhp, FaReact } from "react-icons/fa";
import { SiJira, SiMongodb, SiPostgresql, SiSpringboot, SiTailwindcss, SiTypescript, SiVite } from "react-icons/si";
import type { IconType } from "react-icons";
import { useLanguage } from "../i18n/LanguageContext";

type Skill = readonly [string, string, number, IconType, string];
const skills: readonly Skill[] = [
  ["Java", "Backend", 78, FaJava, "#f59e0b"], ["Spring Boot", "Backend", 74, SiSpringboot, "#86efac"], ["Maven", "Backend", 65, FaCode, "#c4b5fd"], ["JSON", "Backend", 72, FaCode, "#facc15"], ["XML", "Backend", 60, FaCode, "#fb923c"], ["Node.js", "Backend", 70, FaNodeJs, "#4ade80"], ["Express.js", "Backend", 62, FaCode, "#d1d5db"], ["PHP", "Backend", 58, FaPhp, "#a5b4fc"], ["REST API", "Backend", 76, FaCode, "#67e8f9"],
  ["React", "Frontend", 76, FaReact, "#67e8f9"], ["Angular", "Frontend", 61, FaAngular, "#fb7185"], ["HTML", "Frontend", 80, FaHtml5, "#fb923c"], ["CSS", "Frontend", 75, FaCss3Alt, "#60a5fa"], ["JavaScript", "Frontend", 75, FaJsSquare, "#fde047"], ["TypeScript", "Frontend", 64, SiTypescript, "#60a5fa"], ["Bootstrap", "Frontend", 68, FaBootstrap, "#c084fc"], ["Material UI", "Frontend", 62, FaCode, "#38bdf8"], ["Tailwind", "Frontend", 70, SiTailwindcss, "#22d3ee"], ["Vite", "Frontend", 71, SiVite, "#c084fc"],
  ["MySQL", "Data", 62, FaCode, "#38bdf8"], ["SQL", "Data", 68, FaCode, "#facc15"], ["PostgreSQL", "Data", 72, SiPostgresql, "#93c5fd"], ["MongoDB", "Data", 58, SiMongodb, "#86efac"],
  ["Git", "Tooling", 78, FaGitAlt, "#fb923c"], ["GitHub", "Tooling", 70, FaGithub, "#f8fafc"], ["Postman", "Tooling", 64, FaCode, "#fb923c"], ["Docker", "Tooling", 58, FaDocker, "#60a5fa"], ["Linux", "Tooling", 66, FaLinux, "#facc15"], ["Netlify", "Tooling", 61, FaCode, "#5eead4"], ["Jira", "Tooling", 62, SiJira, "#818cf8"], ["Trello", "Tooling", 58, FaCode, "#60a5fa"], ["IntelliJ IDEA", "Tooling", 66, FaCode, "#f472b6"], ["VS Code", "Tooling", 74, FaCode, "#38bdf8"],
] as const;

const SkillsApp = () => {
  const { t } = useLanguage();

  const [active, setActive] = useState(skills[0]);
  const ActiveIcon = active[3];
  const groups = ["Backend", "Frontend", "Data", "Tooling"];
return <div className="text-white"><div className="mb-6"><p className="font-mono text-sm text-cyan-300">// skill_radar.exe</p><h2 className="mt-1 text-3xl font-bold">{t("technicalConstellation")}</h2><p className="mt-2 max-w-2xl text-white/60">{t("skillsDescription")}</p></div><div className="grid gap-6 lg:grid-cols-[270px_1fr]"><div className="relative flex min-h-72 items-center justify-center overflow-hidden rounded-2xl border border-cyan-400/25 bg-slate-950/60"><div className="absolute h-52 w-52 rounded-full border border-cyan-300/15" /><div className="absolute h-36 w-36 rounded-full border border-violet-300/20" /><motion.div animate={{ rotate: 360 }} transition={{ duration: 14, repeat: Infinity, ease: "linear" }} className="absolute h-64 w-64 rounded-full border border-dashed border-violet-300/20" /><div className="relative text-center"><ActiveIcon size={38} style={{ color: active[4] }} className="mx-auto" /><p className="mt-3 font-bold">{active[0]}</p><p className="font-mono text-xs text-white/45">{active[1]} · {active[2]}%</p><div className="mx-auto mt-3 h-1 w-28 overflow-hidden rounded-full bg-white/10"><motion.div animate={{ width: `${active[2]}%` }} className="h-full rounded-full" style={{ backgroundColor: active[4] }} /></div></div></div><div className="space-y-5">{groups.map((group) => <section key={group}><h3 className="mb-2 font-mono text-xs uppercase tracking-[.2em] text-cyan-200/70">{group}</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{skills.filter((skill) => skill[1] === group).map((skill, index) => { const Icon = skill[3]; const selected = skill[0] === active[0]; return <motion.button key={skill[0]} onMouseEnter={() => setActive(skill)} onFocus={() => setActive(skill)} whileHover={{ scale: 1.03, y: -3 }} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .018 }} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition ${selected ? "border-cyan-300/60 bg-cyan-400/10" : "border-white/10 bg-white/5 hover:border-white/25"}`}><Icon size={25} style={{ color: skill[4] }} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{skill[0]}</span><span className="mt-1 block h-1 overflow-hidden rounded-full bg-black/30"><span className="block h-full rounded-full" style={{ width: `${skill[2]}%`, backgroundColor: skill[4] }} /></span></span><span className="font-mono text-xs text-white/45">{skill[2]}%</span></motion.button>; })}</div></section>)}</div></div></div>;};

export default SkillsApp;
